echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "i am practinng git and github for improve myself"
echo "i am proude to be party of this batch-33"
echo "check the testing branch-2 are mergered in master"
echo "it will easily mergerd"
